### ISSUE TITLE
Use wind speed and direction to choose best shutter to open first

### ISSUE THREAD

**Issue by pchote** [warwick-one-metre/domed#1]
TBD:
- What threshold should we enable this for?
- What if the Vaisala isn't available?
- Check if the Vaisala is mounted correctly (https://github.com/warwick-one-metre/docs/issues/71)

**Comment by pchote** [comment]
This logic may be better suited at the OpenROCS / master controller layer.

**Comment by bigastrodaddy** [comment]
start low for everything especially wind speed and humidity.\
no vaisala then close - could try and run with swasp weather station

**Comment by pchote** [comment]
8f859273c49c525150fc15849206e149aa8a9661 allows the ops code to specify the order, so closing here.
